calibs:
  0:
    sweeps:
    - curve: 0.1295166015625
      gibmag: -0.005443572998046875
      gibphase: 1.908203125
      ogeemag: 0.1444091796875
      ogeephase: 2.69921875
      phase: 0.0
      tilt: -0.05224609375
    - curve: 0.45263671875
      gibmag: -0.004119873046875
      gibphase: 2.79296875
      ogeemag: -0.324462890625
      ogeephase: 0.6015625
      phase: -0.0048675537109375
      tilt: 0.0428466796875
    uid: 3940089819
  1:
    sweeps:
    - curve: -0.1484375
      gibmag: -0.0033092498779296875
      gibphase: 2.3359375
      ogeemag: -0.2491455078125
      ogeephase: 0.6591796875
      phase: 0.0
      tilt: -0.046905517578125
    - curve: 0.33984375
      gibmag: -0.0023899078369140625
      gibphase: 2.150390625
      ogeemag: -0.2115478515625
      ogeephase: 1.287109375
      phase: -0.0004146099090576172
      tilt: 0.0496826171875
    uid: 3220422702
  2:
    sweeps:
    - curve: 0.04022216796875
      gibmag: 0.00505828857421875
      gibphase: 1.1923828125
      ogeemag: -0.55029296875
      ogeephase: 1.232421875
      phase: 0.0
      tilt: -0.0489501953125
    - curve: 0.431396484375
      gibmag: 0.005184173583984375
      gibphase: 2.42578125
      ogeemag: -0.50244140625
      ogeephase: 2.015625
      phase: -0.003009796142578125
      tilt: 0.045074462890625
    uid: 565045534
  3:
    sweeps:
    - curve: 0.1756591796875
      gibmag: 0.006053924560546875
      gibphase: 0.420166015625
      ogeemag: -0.521484375
      ogeephase: 0.81298828125
      phase: 0.0
      tilt: -0.045074462890625
    - curve: 0.599609375
      gibmag: 0.004619598388671875
      gibphase: 1.5546875
      ogeemag: -0.5078125
      ogeephase: 1.5166015625
      phase: -0.0025920867919921875
      tilt: 0.04296875
    uid: 2951563617
geos:
  0:
    origin:
    - 1.715815544128418
    - 1.5928784608840942
    - 2.416675090789795
    rotation:
    - - -0.6931701898574829
      - 0.6678827404975891
      - -0.27101242542266846
    - - -0.5721214413642883
      - -0.7385317087173462
      - -0.3567183315753937
    - - -0.43839728832244873
      - -0.09221450239419937
      - 0.894038200378418
  1:
    origin:
    - -2.203197956085205
    - -1.2621325254440308
    - 2.4208390712738037
    rotation:
    - - 0.7466049790382385
      - -0.5518090128898621
      - 0.37160173058509827
    - - 0.4634549617767334
      - 0.8321449756622314
      - 0.304539293050766
    - - -0.4772740602493286
      - -0.05514988675713539
      - 0.8770222067832947
  2:
    origin:
    - -1.8708196878433228
    - 1.6264663934707642
    - 2.4243221282958984
    rotation:
    - - 0.5714756846427917
      - 0.7838044166564941
      - 0.24303539097309113
    - - -0.531158447265625
      - 0.5790553689002991
      - -0.6185188889503479
    - - -0.6255287528038025
      - 0.22437818348407745
      - 0.7472403645515442
  3:
    origin:
    - 2.141777992248535
    - -1.3453538417816162
    - 2.4410531520843506
    rotation:
    - - -0.7221572399139404
      - -0.5552648305892944
      - -0.4125165641307831
    - - 0.5316485166549683
      - -0.8270592093467712
      - 0.18254558742046356
    - - -0.4425368010997772
      - -0.08748719841241837
      - 0.892472505569458
systemType: 2
type: lighthouse_system_configuration
version: '1'
